/** @type {import('tailwindcss').Config} */
export default {
    content: [
      "./index.html",
      "./src/**/*.{js,ts,jsx,tsx}",
    ],
    darkMode: "class",
    theme: {
        extend: {
            "colors": {
                "on-primary-fixed": "#003840",
                "surface-container-highest": "#262626",
                "on-error-container": "#ffa8a3",
                "on-secondary-fixed-variant": "#00655d",
                "on-tertiary-fixed-variant": "#790010",
                "on-surface": "#ffffff",
                "primary": "#81ecff",
                "on-tertiary-fixed": "#3a0004",
                "surface-dim": "#0e0e0e",
                "error": "#ff716c",
                "on-surface-variant": "#adaaaa",
                "tertiary-fixed": "#ff928c",
                "primary-container": "#00e3fd",
                "inverse-primary": "#006976",
                "inverse-surface": "#fcf9f8",
                "inverse-on-surface": "#565555",
                "on-primary": "#005762",
                "surface-container-high": "#201f1f",
                "surface-bright": "#2c2c2c",
                "secondary-container": "#006a62",
                "tertiary-container": "#f94d4e",
                "surface-variant": "#262626",
                "tertiary": "#ff716c",
                "error-container": "#9f0519",
                "on-tertiary": "#490006",
                "surface-container-low": "#131313",
                "on-tertiary-container": "#110000",
                "surface": "#0e0e0e",
                "background": "#0e0e0e",
                "secondary-dim": "#72e4d7",
                "on-secondary-container": "#dcfff9",
                "error-dim": "#d7383b",
                "primary-fixed-dim": "#00d4ec",
                "on-primary-fixed-variant": "#005762",
                "tertiary-dim": "#ff716c",
                "surface-container-lowest": "#000000",
                "secondary": "#81f3e5",
                "surface-container": "#1a1919",
                "primary-fixed": "#00e3fd",
                "secondary-fixed-dim": "#72e4d7",
                "surface-tint": "#81ecff",
                "on-secondary-fixed": "#004640",
                "primary-dim": "#00d4ec",
                "secondary-fixed": "#81f3e5",
                "on-primary-container": "#004d57",
                "outline-variant": "#484847",
                "tertiary-fixed-dim": "#ff7b75",
                "on-secondary": "#005a53",
                "on-background": "#ffffff",
                "on-error": "#490006",
                "outline": "#767575"
            },
            "borderRadius": {
                "DEFAULT": "0.125rem",
                "lg": "0.25rem",
                "xl": "0.5rem",
                "full": "0.75rem"
            },
            "fontFamily": {
                "headline": ["Space Grotesk", "sans-serif"],
                "body": ["Manrope", "sans-serif"],
                "label": ["Inter", "sans-serif"]
            }
        },
    },
    plugins: [],
}
